In [1]:
import pandas as pd

In [2]:
sharksdf = pd.read_csv("input/GSAF5.csv", engine="python")
pd.set_option('display.max_rows', 500) 
pd.set_option('display.max_columns', 500)

In [3]:
missing_values = sharksdf.isnull().sum()
print(missing_values)

Case Number                  0
Date                         0
Year                         0
Type                         0
Country                     43
Area                       402
Location                   496
Activity                   527
Name                       200
Sex                        567
Age                       2681
Injury                      27
Fatal (Y/N)                 19
Time                      3213
Species                   2934
Investigator or Source      15
pdf                          0
href formula                 1
href                         3
Case Number.1                0
Case Number.2                0
original order               0
Unnamed: 22               5991
Unnamed: 23               5990
dtype: int64

In [4]:
sharksdf = sharksdf.drop(columns=["href formula","href","Case Number.1","Case Number.2","Unnamed: 22","Unnamed: 23"])

In [5]:
print(sharksdf["Age"].value_counts())

17                         148
18                         145
19                         138
20                         136
15                         135
16                         134
21                         115
22                         113
24                         103
25                         101
14                          97
13                          91
26                          80
23                          80
27                          78
28                          77
29                          75
30                          74
12                          70
32                          64
35                          64
10                          51
31                          50
40                          50
38                          47
34                          45
43                          43
36                          41
33                          40
37                          37
39                          37
42                          36
9                           35
11                          35
52                          34
41                          34
50                          32
45                          32
44                          29
47                          28
8                           27
49                          27
48                          25
46                          25
7                           21
55                          20
51                          19
57                          14
60                          14
6                           14
54                          14
53                          13
58                          12
61                          11
59                          11
56                           9
63                           9
69                           8
Teen                         8
62                           8
5                            7
30s                          7
20s                          6
70                           6
68                           6
teen                         5
3                            4
65                           4
64                           4
66                           3
71                           3
77                           3
young                        2
40s                          2
                             2
8 or 10                      2
F                            2
74                           2
78                           2
7 or 8                       2
1                            2
50s                          2
75                           2
? & 19                       1
                             1
12 or 13                     1
30 & 32                      1
Both 11                      1
33 or 37                     1
36 & 23                      1
28, 23 & 30                  1
86                           1
72                           1
13 or 14                     1
84                           1
18 months                    1
87                           1
Ca. 33                       1
17 & 16                      1
2½                           1
34 & 19                      1
21, 34,24 & 35               1
50 & 30                      1
13 or 18                     1
21 & ?                       1
2 to 3 months                1
10 or 12                     1
33 & 37                      1
"middle-age"                 1
mid-20s                      1
18 or 20                     1
25 or 28                     1
73                           1
(adult)                      1
M                            1
9 or 10                      1
37, 67, 35, 27,  ? & 27      1
20?                          1
Teens                        1
21 or 26                     1
mid-30s                      1
23 & 20                      1
32 & 30                      1
17 & 35                      1
X                            1
60s                          1
23 & 26                      1
16 to 18                     1
28 & 26                      1
?    &   14                  1
46 & 34                      1
Elderly                      1
31 or 33                     1
adult                        1
A.M.                         1
"young"                      1
6½                           1
36 & 26                      1
30 or 36                     1
18 to 22                     1
9 months                     1
25 to 35                     1
33 & 26                      1
67                           1
>50                          1
                             1
MAKE LINE GREEN              1
7      &    31               1
60's                         1
9 & 12                       1
81                           1
Name: Age, dtype: int64

In [6]:
from funciones import fixAge
dfCleanAge = pd.DataFrame(sharksdf["Age"].apply(fixAge))

            Age
0            16
1            36
2            43
3           nan
4           nan
5           nan
6           60s
7            51
8            50
9            12
10          nan
11            9
12           22
13           25
14           37
15           20
16           49
17           15
18           21
19           22
20           40
21           72
22          nan
23           43
24           18
25           29
26           36
27          nan
28           31
29          nan
30            9
31           11
32          nan
33          nan
34           10
35          nan
36           59
37          nan
38           42
39           34
40           35
41           11
42           59
43           43
44           42
45          nan
46          nan
47           19
48            6
49           19
50           27
51           64
52           60
53           23
54          nan
55          nan
56           29
57           52
58           13
59           57
60           22
61           11
62           48
63           23
64           59
65           39
66           24
67           15
68          nan
69           12
70           26
71           26
72           69
73           60
74           34
75          nan
76           46
77           22
78           16
79           41
80            9
81          nan
82           19
83           45
84           12
85          nan
86           41
87           21
88           31
89          nan
90           65
91          nan
92           45
93           40
94          nan
95          nan
96           15
97          nan
98          nan
99           48
100         nan
101          11
102          31
103         nan
104          38
105          71
106          43
107          32
108          58
109         nan
110          26
111          22
112         nan
113         nan
114          28
115          20
116           9
117          54
118          28
119          19
120          50
121          10
122          42
123          21
124          21
125          35
126          32
127          44
128         nan
129           9
130          25
131         nan
132          18
133          22
134          13
135          14
136          22
137           7
138         nan
139          14
140          27
141          12
142          16
143         nan
144          20
145          42
146          50
147          29
148          62
149         nan
150          37
151         nan
152          54
153          21
154         nan
155          38
156          15
157          10
158          22
159          10
160          57
161          52
162          25
163          35
164          46
165          31
166         40s
167          45
168          34
169          38
170          39
171         nan
172          23
173          32
174          52
175          32
176          68
177         nan
178          12
179          18
180          19
181         nan
182          23
183          43
184          19
185          47
186           6
187          37
188           9
189          36
190          10
191          16
192          12
193         nan
194          13
195          11
196          17
197          47
198          14
199          19
200          19
201          13
202          18
203          30
204          50
205         nan
206         nan
207          29
208          65
209          63
210          26
211          71
212          48
213         nan
214          13
215          23
216          70
217          43
218          36
219          52
220          58
221           9
222         nan
223          36
224   18 months
225         nan
226          22
227          41
228          35
229         nan
230          57
231          20
232         nan
233         nan
234         nan
235         nan
236          17
237          38
238          34
239          15
240          12
241         nan
242          17
243         nan
244         nan
245          50
246         40s
247         nan
248          17
249         nan
...         ...
5742        nan
5743        nan
5744        nan
5745        nan
5746        nan
5747          1
5748        nan
5749        nan
5750        nan
5751        nan
5752        nan
5753        nan
5754        nan
5755        nan
5756        nan
5757        nan
5758        nan
5759        nan
5760        nan
5761        nan
5762         15
5763        nan
5764        nan
5765         19
5766        nan
5767        nan
5768        nan
5769        nan
5770        nan
5771        nan
5772        nan
5773        nan
5774        nan
5775        nan
5776        nan
5777        nan
5778        nan
5779        nan
5780     7 or 8
5781        nan
5782        nan
5783        nan
5784        nan
5785        nan
5786        nan
5787        nan
5788        nan
5789        nan
5790         29
5791        nan
5792         12
5793        nan
5794        nan
5795        nan
5796        nan
5797        nan
5798        nan
5799        nan
5800        nan
5801        nan
5802         52
5803        nan
5804        nan
5805        nan
5806        nan
5807         17
5808        nan
5809        nan
5810        nan
5811        nan
5812        nan
5813        nan
5814        nan
5815        nan
5816        nan
5817        nan
5818        nan
5819        nan
5820        nan
5821        nan
5822        nan
5823         22
5824        nan
5825        nan
5826        nan
5827        nan
5828        nan
5829        nan
5830        nan
5831        nan
5832        nan
5833        nan
5834        nan
5835        nan
5836        nan
5837      young
5838        nan
5839        nan
5840        nan
5841        nan
5842        nan
5843        nan
5844         14
5845        nan
5846        nan
5847        nan
5848        nan
5849        nan
5850        nan
5851         19
5852        nan
5853        nan
5854        nan
5855        nan
5856        nan
5857        nan
5858        nan
5859        nan
5860        nan
5861        nan
5862        nan
5863        nan
5864        nan
5865        nan
5866        nan
5867        nan
5868        nan
5869        nan
5870        nan
5871        nan
5872        nan
5873        nan
5874         20
5875        nan
5876        nan
5877        nan
5878        nan
5879         15
5880        nan
5881        nan
5882        nan
5883        nan
5884        nan
5885        nan
5886        nan
5887        nan
5888        nan
5889        nan
5890         21
5891        nan
5892        nan
5893        nan
5894        nan
5895        nan
5896        nan
5897        nan
5898        nan
5899        nan
5900        nan
5901        nan
5902        nan
5903        nan
5904        nan
5905        nan
5906        nan
5907        nan
5908        nan
5909        nan
5910        nan
5911        nan
5912        nan
5913        nan
5914        nan
5915        nan
5916         19
5917        nan
5918        nan
5919        nan
5920        nan
5921        nan
5922        nan
5923        nan
5924        nan
5925        nan
5926        nan
5927        nan
5928         27
5929         36
5930        nan
5931         25
5932          6
5933         16
5934        nan
5935        nan
5936        nan
5937        nan
5938        nan
5939        nan
5940        nan
5941        nan
5942        nan
5943        nan
5944         50
5945        nan
5946        nan
5947        nan
5948        nan
5949        nan
5950        nan
5951        nan
5952        nan
5953        nan
5954        nan
5955   13 or 14
5956        nan
5957        nan
5958        nan
5959        nan
5960        nan
5961        nan
5962        nan
5963        nan
5964        nan
5965        nan
5966         16
5967        nan
5968        nan
5969        nan
5970        nan
5971        nan
5972        nan
5973        nan
5974        nan
5975        nan
5976        nan
5977        nan
5978        nan
5979        nan
5980        nan
5981        nan
5982        nan
5983        nan
5984        nan
5985        nan
5986        nan
5987        nan
5988        nan
5989        nan
5990        nan
5991         15

[5992 rows x 1 columns]

In [8]:
print(dfCleanAge["Age"].value_counts())

nan                        2681
17                          148
18                          145
19                          138
20                          136
15                          135
16                          134
21                          115
22                          113
24                          103
25                          101
14                           97
13                           91
26                           80
23                           80
27                           78
28                           77
29                           75
30                           74
12                           70
32                           64
35                           64
10                           51
40                           50
31                           50
38                           47
34                           45
43                           43
36                           41
33                           40
39                           37
37                           37
42                           36
11                           35
9                            35
52                           34
41                           34
45                           32
50                           32
44                           29
47                           28
8                            27
49                           27
48                           25
46                           25
7                            21
55                           20
51                           19
6                            14
60                           14
57                           14
54                           14
53                           13
58                           12
61                           11
59                           11
56                            9
63                            9
69                            8
16                            8
62                            8
5                             7
30s                           7
68                            6
20                            6
70                            6
teen                          5
65                            4
64                            4
3                             4
66                            3
77                            3
71                            3
8 or 10                       2
F                             2
75                            2
40s                           2
7 or 8                        2
74                            2
young                         2
50s                           2
                              2
78                            2
1                             2
12 or 13                      1
36 & 23                       1
? & 19                        1
                              1
28, 23 & 30                   1
13 or 18                      1
33 or 37                      1
87                            1
13 or 14                      1
36 & 26                       1
17 & 16                       1
mid-20s                       1
72                            1
30 & 32                       1
Both 11                       1
18 months                     1
2½                            1
21, 34,24 & 35                1
50 & 30                       1
Ca. 33                        1
84                            1
"middle-age"                  1
33 & 37                       1
10 or 12                      1
2 to 3 months                 1
86                            1
34 & 19                       1
21 & ?                        1
6½                            1
18 or 20                      1
23 & 26                       1
46 & 34                       1
(adult)                       1
37, 67, 35, 27,  ? & 27       1
20?                           1
Teens                         1
21 or 26                      1
17 & 35                       1
mid-30s                       1
M                             1
23 & 20                       1
32 & 30                       1
28 & 26                       1
X                             1
60s                           1
?    &   14                   1
16 to 18                      1
9 or 10                       1
Elderly                       1
25 or 28                      1
67                            1
73                            1
A.M.                          1
"young"                       1
30 or 36                      1
18 to 22                      1
adult                         1
9 months                      1
>50                           1
31 or 33                      1
25 to 35                      1
60's                          1
                              1
MAKE LINE GREEN               1
7      &    31                1
9 & 12                        1
33 & 26                       1
81                            1
Name: Age, dtype: int64